### ISSUE TITLE
Callback should be the last argument

### ISSUE THREAD

**Issue by yadomi** [pitzzae/allocine-crawler#1]
Nice scrapper, however why put the callback as first argument ? This not very node-friendly since tools like [util.promisfy](https://nodejs.org/api/util.html#util_util_promisify_original) or the [bluebird one](http://bluebirdjs.com/docs/api/promise.promisify.html) won't be able to transform the function to promise :'(

**Comment by pitzzae** [comment]
I wrote part of the code following the update of the frontend 'allocine', the methods are now in the form of promise
